### ISSUE TITLE
help meh

### ISSUE THREAD

**Issue by nqthqn** [OverlappingElvis/15th-night#1]
:cry: :cry: 
:cry: :cry: 

```
nathann@ohm 15th-night (master) $ node .
module.js:329
    throw err;
    ^

Error: Cannot find module '../../server/tokens'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at module.exports (/Users/nathann/code/15th-night/common/models/provider.js:4:15)
    at /Users/nathann/code/15th-night/node_modules/loopback-boot/lib/executor.js:229:11
    at Array.forEach (native)
    at defineModels (/Users/nathann/code/15th-night/node_modules/loopback-boot/lib/executor.js:207:23)
    at setupModels (/Users/nathann/code/15th-night/node_modules/loopback-boot/lib/executor.js:175:3)
    at execute (/Users/nathann/code/15th-night/node_modules/loopback-boot/lib/executor.js:33:3)
```

**Comment by OverlappingElvis** [comment]
@natsn You need to create an app in Tropo with outbound permissions, then create a `server/tokens.json` file from the example `server/tokens.example.json` file.
